name: biome

on:
  pull_request:
    paths:
      - 'source/**/*.ts'
      - 'source/**/*.tsx'
      - 'source/**/*.js'
      - 'source/**/*.vue'
      - 'source/package.json'
      - 'source/pnpm-lock.yaml'

jobs:
  biome:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: source

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: enable pnpm
        run: corepack enable

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build assets
        run: pnpm lint:check